hash-format = "sha256"

[[files]]
file = "mods/adorn.toml"
hash = "662c39e5315f4960d7ff2d01f2dd903c2c13d372ecfadcd095919bb8066d941b"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "4680675c5c1f41e92d4a98a2d8ad06e17f645cb1172a32162094478a4fe684d2"
metafile = true

[[files]]
file = "mods/antique-atlas.toml"
hash = "5734c75123b29b303c9fef02d4668bb145a838a3121a3af51bd1ea5265665ba3"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "cc685edcd69b5d59fdb53bd09d3231164da6468b37a67ff4066457a51785f88c"
metafile = true

[[files]]
file = "mods/artificial-foliage.toml"
hash = "dce7cb36dd5c088f7810c415265a2aa63767305efffcb377a7c9fae949d53269"
metafile = true

[[files]]
file = "mods/bedspreads-fabric.toml"
hash = "c85c950c882ad8f957926dc1f010f0b022a03a31b7390cd1adf79ce35ebd0747"
metafile = true

[[files]]
file = "mods/beebuddy.toml"
hash = "584fc4e3bfd4bc820ccc7701a40f4777008b7d9c60c14deca2391c3d04c79846"
metafile = true

[[files]]
file = "mods/besmirchment.toml"
hash = "ecbcb160c240c89eed285e2e6996245029a82cac4cddd8c7e1a695f9590ffc75"
metafile = true

[[files]]
file = "mods/better-beds.toml"
hash = "c8229b294a71b966527019d290f58a2abac240c15897dc6b298dd9cdc975124d"
metafile = true

[[files]]
file = "mods/bewitchment.toml"
hash = "3b91f91f4f4d825dbcf70616950f77dbe566dc71b264919a7475d756bc047961"
metafile = true

[[files]]
file = "mods/biome-makeover.toml"
hash = "c215b7911fcaeb65fe09bfb120bba1a9097977b8162ae01eaf31857531208b46"
metafile = true

[[files]]
file = "mods/blockus.toml"
hash = "484ba093dc075e7b73b392004bb22feb15bcb5105d16014bd7337400882a865b"
metafile = true

[[files]]
file = "mods/campanion.toml"
hash = "d317d91c62c1d8b150464d8cdd3403f42daeda15b58f43971bede0b83afe42ce"
metafile = true

[[files]]
file = "mods/cardinal-components.toml"
hash = "5e3df1b6812a6d79afc83f96047f02563363c9eb36dbeec6460274fb17289b88"
metafile = true

[[files]]
file = "mods/chest-cavity.toml"
hash = "9a2fcd936c4b715ba3b08432d71e922e0d0275a17ebd52c8ef1ca319a1a18712"
metafile = true

[[files]]
file = "mods/cinderscapes.toml"
hash = "d7b97d8b30d125d2f9a90fb6c58d5393d398711c1e16cc9d8c6936be256c66bf"
metafile = true

[[files]]
file = "mods/cleancut.toml"
hash = "c880885c38695412ceab953579b58dd29b43d68d4e560a3e6944cde1d76bac81"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "4ac362da27727d78e5105fe2a2da78db6926aacddf1377bd662eb154a31e63f8"
metafile = true

[[files]]
file = "mods/comforts-fabric.toml"
hash = "33ced83e0f82567e7ad5bee19301bb9461ff8b75b457946a1dad24350cef0625"
metafile = true

[[files]]
file = "mods/couplings.toml"
hash = "3ad2b47b9dae178532fbd287623baad8313ad576ba5afaaacbd9b4572099298c"
metafile = true

[[files]]
file = "mods/creeper-spores.toml"
hash = "4fd196dad54f6f9cf3d08ab84f9f605f1f1d261cb9523e42aa11f5858bef98ea"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "a27f1249331e73fd51dfe948a9f87121ee99abeb7721019124bfa7a07b745642"
metafile = true

[[files]]
file = "mods/delicious-dishes.toml"
hash = "db5fac189b6ab05445ad5868860eb7dbafc7dcab46c452fee15957745f48c522"
metafile = true

[[files]]
file = "mods/disfabric.toml"
hash = "4b8dcaddab4548684e48bd036880e2ca38b5ad0639af71a6627a5d6c8188b931"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "d0b9148b7ab3ae0f3e62a9b851dde3911c28d6010b7c69766fe9c13ecdb9e263"
metafile = true

[[files]]
file = "mods/easiervillagertrading.toml"
hash = "c9247c84faa7803f774e6d0e212f5515f807fbf859f78bf616a288f43536b815"
metafile = true

[[files]]
file = "mods/eldritch-mobs.toml"
hash = "dc4f91c34af1a2a94818ba03df51c65861518e97173a17abab25851e99da0f7a"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "800c79b73ae37d0967cdc1df1f7725d62a64b9fea1729dcea35ba0a77d0c2ae4"
metafile = true

[[files]]
file = "mods/extra-alchemy.toml"
hash = "0a711e4e93574361a6ba7b7d698bcd234c01aad70df50fa83e4748f66be1dd48"
metafile = true

[[files]]
file = "mods/extra-origins.toml"
hash = "2340ed289f08b37ad5b9e57b75e644f3b1cf56540e4415dfc2184a57e1f0a5b0"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "6fab6178e8f058ca81885c4b21e8cf979324cea44cc96ce324cc2490668925d1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "fc01dca8a92724ac74d2a848b3aa06e70a3b05cb10fdb91c684abe684459ac1a"
metafile = true

[[files]]
file = "mods/fabric-waystones.toml"
hash = "f8997a639bf02a50bc4c2a032f2dda510cad2652a47d492e63452af0776c9488"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "6a54f6f39e406eadc55630808a678b13b43ca3d057e8f13e1ddcbae6f84ac9bc"
metafile = true

[[files]]
file = "mods/fastchest.toml"
hash = "1795f80308062a53a66fbbac40ddaf1043aca00ef3907785b0a5435bfb08f360"
metafile = true

[[files]]
file = "mods/figura.toml"
hash = "9b49dccf499260114af704e9e03f665b02f7b955ee9fea429eaa9ad10ac80565"
metafile = true

[[files]]
file = "mods/geckolib-fabric.toml"
hash = "f83e1ad11653a5711a9796e338484b0c1424f202f049d5bfcdaf49b3651d8ddb"
metafile = true

[[files]]
file = "mods/geckolib.toml"
hash = "cacfd248d0fc8b89764354e3522c07aa5e85e0e881b18c2ad1319d8a8ccd1aba"
metafile = true

[[files]]
file = "mods/golemancy.toml"
hash = "5b28f52cd9142401df414d5352975a305adb301d57ca529a62010dc11b73bb95"
metafile = true

[[files]]
file = "mods/grind-enchantments.toml"
hash = "44761d96cd571b878060b2bfdc86643ce6ad9f855fda3cabd40e3578e17853b9"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "153cda3c6d61ae9b32117fe5315ee40a0bd561b7292d9a5927773a368b52c254"
metafile = true

[[files]]
file = "mods/impersonate.toml"
hash = "ccd40f3fb3b725f5e1807b3cdf82a0915630d6904661278dafa5d416afc82fb4"
metafile = true

[[files]]
file = "mods/inmis.toml"
hash = "d81a709054e5a9b0613475dc99ff088d7f6585677d1b5e6643f9edc837795b65"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "cd086454ecc029769982aeed7bb136883180c477bc6d177c5efff773e39b3a98"
metafile = true

[[files]]
file = "mods/lakeside.toml"
hash = "2ab9e0e9be9e282c807d8d4bf4258cd9bcbb4c1ecd4f8ec8b7a869c74c22701c"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/light-overlay.toml"
hash = "70039054cb7df229995231d349d36d120bf21e77cc36582acf84c7d06ed82591"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "08f60b30a7267de38af1c8780bb0932e02fa0bafbb49290d8c224fb2102415ed"
metafile = true

[[files]]
file = "mods/miskatonic-mysteries-fabric.toml"
hash = "f3d7080f905590451149776cc663600bd326c2f9b70c0370d6b0c2fa95e6ff05"
metafile = true

[[files]]
file = "mods/mo-glass.toml"
hash = "bddfd4dcebb2b051aaf999895875cad37076733174d38f68b01b61a40d7c07c0"
metafile = true

[[files]]
file = "mods/mo-structures.toml"
hash = "16048a85ecb39fe88f3790e82ea6e57223ed3c860318d565c085d2b93da71f60"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "89f3e405702e97fbea8f83e9a11ef245bff1b90fa612f70362e85792fa4606ed"
metafile = true

[[files]]
file = "mods/natures-compass.toml"
hash = "3461fecc495e9c7fd66b8423c1307fb12b1d2da87cc7ceaec8c48ff605dd4619"
metafile = true

[[files]]
file = "mods/nomad-books.toml"
hash = "c89e94eec39b0cdb6d40f8ccbcf5aca2d9ad8340b142d559acc93607fb2b8b9e"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "48801db07e7f0352c9a155aa236c01a48b85e638424d41c89a02a7cdcd1266ad"
metafile = true

[[files]]
file = "mods/origins-classes.toml"
hash = "caacad566b5921e6e615d5e1f4c11f0a8d7ea5a3bb77f6ff43e8cf5880aa73aa"
metafile = true

[[files]]
file = "mods/origins.toml"
hash = "e4d76939a618d319771c58db67866281c8eafbe90835701c838bcc1a24023782"
metafile = true

[[files]]
file = "mods/patchouli-fabric.toml"
hash = "e7586ef828628b4b3b81ad768517e6fda84e1523e7e3dcbb29086b5e1c668939"
metafile = true

[[files]]
file = "mods/pehkui.toml"
hash = "0f3d035064bce6f25d8a3db9c5b11091a0934b26ee7d3dc55f760b4cdffe3850"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "fc6d55dfad363110ca81ffda6510dac8aa3cecdad04d0ded6ed9e706764b2825"
metafile = true

[[files]]
file = "mods/randompatches-fabric.toml"
hash = "81179fc5374e1649cb8bb169226227bf5564be26b4f40702537d4512467c1ca8"
metafile = true

[[files]]
file = "mods/rats-mischief.toml"
hash = "b3e1675b2fab20be98830b2b0fd736bea84f0cbf33d1d20e111dd027efd201a2"
metafile = true

[[files]]
file = "mods/respawnable-pets.toml"
hash = "4dec297a2a3d3310a84b16692ac70d79b42f5235becd434c6d2f5995f8e09619"
metafile = true

[[files]]
file = "mods/river-redux.toml"
hash = "6d7d80ccba1aa9fe1cf1bee4a81efbaf29742fdcbbb9d8d5bd80114a030c62c3"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
hash = "3388f1488460e5d2d16e9c079db90258179ec4ec221fb8d75f5a6d769908990d"
metafile = true

[[files]]
file = "mods/sandwichable.toml"
hash = "2fca7f552d1c94abd9e43c35d8b713930cb17f0fa711b83d14ac8b21d66d4579"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
hash = "c9fdbed1b17e1770f120fab89eaac4b769a3656b562c109890c18cc710991e44"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "d02b56170076cc508fe31ff0e4d36b4576cb0ae7cf2c008b273cd64c34787408"
metafile = true

[[files]]
file = "mods/snow-under-trees-fabric.toml"
hash = "6bdac5ef84c96fc51529588f1eb0ff4b352e41248d04fb13bc38d9091aa185cc"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "e8bd65dbaa1cec8da1df4f903b8dc1a9db5aca82e56856c06fc284ff1b9a9a73"
metafile = true

[[files]]
file = "mods/somnus.toml"
hash = "692215c64ba4b8d75b493ac6c352c404664daf3d8092d9692aec0803442af911"
metafile = true

[[files]]
file = "mods/spellbound-enchantments.toml"
hash = "c5ba7ce46c5eeeb03c1140eabe77b8156ec1aafc9d82502d6b0a61ca47aebc88"
metafile = true

[[files]]
file = "mods/terrestria.toml"
hash = "702bfe08f863681ac7d921b58acb31aa2e9a79ce35ac75354e0d0d6b0780461f"
metafile = true

[[files]]
file = "mods/trap-expansion-fabric.toml"
hash = "5033ae0180e23ca31a148372e3316efbe41293546567168a396872e84d35f519"
metafile = true

[[files]]
file = "mods/traverse.toml"
hash = "6a9a5690cb50bf6f73911300a08cc1ccd97ec206482ccf09b5b33dee62a3c791"
metafile = true

[[files]]
file = "mods/trinkets-fabric.toml"
hash = "8953fba700f6c02da2795545b484429e4c772f49048db0b89905e52807c44ae7"
metafile = true

[[files]]
file = "mods/villagers-follow-emeralds-fabric.toml"
hash = "91c7a8252a864acb6170f84df2c6e0f329dc73585490bb43fd3f5a66f9fbbb68"
metafile = true

[[files]]
file = "mods/wandering-collector.toml"
hash = "c8928b92961c43c8a7225a2cf781a274366166ddb5cfaeb2f4c5c7bd27c6f34d"
metafile = true

[[files]]
file = "mods/wthit.toml"
hash = "cb8e8c9c82a018c6184a114f6c607375785643a545a44b86a0ae510e27640f09"
metafile = true

[[files]]
file = "mods/xl-packets-fabric.toml"
hash = "3638004d576785608b0f70a494204569df050469d2aef50480ef29aa08d0c35d"
metafile = true

[[files]]
file = "mods/yungs-api-fabric.toml"
hash = "e2a0f46ae4443992bdc0d49da9b42f01115261ae24821d56397c28211fd67311"
metafile = true

[[files]]
file = "mods/yungs-better-caves-fabric.toml"
hash = "42e7435ac40618706808a5d3622093efa273ac2f3af0826c36a28ec8814904e6"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-fabric.toml"
hash = "fdb874f95c9f7b466cde9ef846b8b1636ebc235b00702a679c482e836e9e6730"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-fabric.toml"
hash = "5d3d3201b8b9673c732a59579d49c237112989dd87776879aa6c6e58609de201"
metafile = true
