name = "Wool SMP"
author = "Exo"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e65f1c355459d5496b80cda20bc88c3be3a885b6e5e6f3a060c79e2e25d2d183"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
