name = "Wool SMP"
author = "Exo"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e60ea325b44e801b3692fba2fcee8032857f91bbc31559b5a0d4b0e692bb77e9"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
