name = "Wool SMP"
author = "Exo"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cff7cbf735414beb26c5a18b1215fe6cb04d800aea63e3ce1290c6285960cc13"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4", "1.16.3", "1.16.2"]
