name = "All Stone to Tools"
filename = "StoneToToolsFabric-1.16.5-2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3363/244/StoneToToolsFabric-1.16.5-2.1.jar"
hash-format = "murmur2"
hash = "3253677089"

[update]
[update.curseforge]
file-id = 3363244
project-id = 451571
release-channel = "beta"
