name = "Bee Buddies"
filename = "beebuddy-1.1.3+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3382/25/beebuddy-1.1.3+1.16.5.jar"
hash-format = "murmur2"
hash = "1264225800"

[update]
[update.curseforge]
file-id = 3382025
project-id = 496221
release-channel = "beta"
