name = "Besmirchment"
filename = "besmirchment-1.16.5-8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3334/844/besmirchment-1.16.5-8.jar"
hash-format = "murmur2"
hash = "495742447"

[update]
[update.curseforge]
file-id = 3334844
project-id = 462160
release-channel = "beta"
