name = "Chest Cavity"
filename = "chestcavity-2.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3327/400/chestcavity-2.12.2.jar"
hash-format = "murmur2"
hash = "3412919433"

[update]
[update.curseforge]
file-id = 3327400
project-id = 408480
release-channel = "beta"
