name = "Comforts (Fabric)"
filename = "comforts-fabric-0.0.3-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3311/305/comforts-fabric-0.0.3-1.16.5.jar"
hash-format = "murmur2"
hash = "2509656659"

[update]
[update.curseforge]
file-id = 3311305
project-id = 433539
release-channel = "beta"
