name = "Delicious Dishes"
filename = "dishes-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3061/102/dishes-2.0.0.jar"
hash-format = "murmur2"
hash = "2488165927"

[update]
[update.curseforge]
file-id = 3061102
project-id = 390141
release-channel = "beta"
