name = "DisFabric"
filename = "disfabric-1.16.5-1.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/399/disfabric-1.16.5-1.2.5.jar"
hash-format = "murmur2"
hash = "3538513366"

[update]
[update.curseforge]
file-id = 3248399
project-id = 399520
release-channel = "beta"
