name = "Eldritch Mobs"
filename = "eldritch-mobs-1.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3329/930/eldritch-mobs-1.8.0.jar"
hash-format = "murmur2"
hash = "4259623242"

[update]
[update.curseforge]
file-id = 3329930
project-id = 392015
release-channel = "beta"
