name = "Fabric Waystones"
filename = "wraith-waystones-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3350/982/wraith-waystones-2.0.1.jar"
hash-format = "murmur2"
hash = "1376681555"

[update]
[update.curseforge]
file-id = 3350982
project-id = 410902
release-channel = "beta"
