name = "Fabric API"
filename = "fabric-api-0.37.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3386/463/fabric-api-0.37.0+1.16.jar"
hash-format = "murmur2"
hash = "1462276005"

[update]
[update.curseforge]
file-id = 3386463
project-id = 306612
release-channel = "beta"
