name = "FallingTree (Forge&Fabric)"
filename = "FallingTree-1.16.5-2.11.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/236/FallingTree-1.16.5-2.11.5.jar"
hash-format = "murmur2"
hash = "87328117"

[update]
[update.curseforge]
file-id = 3349236
project-id = 349559
release-channel = "beta"
