name = "Figura"
filename = "figura-0.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3390/112/figura-0.0.6.jar"
hash-format = "murmur2"
hash = "809850614"

[update]
[update.curseforge]
file-id = 3390112
project-id = 451616
release-channel = "beta"
