name = "GeckoLib [FABRIC]"
filename = "geckolib-fabric-1.16.5-3.0.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3371/313/geckolib-fabric-1.16.5-3.0.42.jar"
hash-format = "murmur2"
hash = "3613008982"

[update]
[update.curseforge]
file-id = 3371313
project-id = 398667
release-channel = "beta"
