name = "Golemancy"
filename = "golemancy-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/215/golemancy-1.0.1.jar"
hash-format = "murmur2"
hash = "3352348434"

[update]
[update.curseforge]
file-id = 3245215
project-id = 457403
release-channel = "beta"
