name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.7.3-newconfig.2+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3398/487/mousewheelie-1.7.3-newconfig.2+mc1.16.5.jar"
hash-format = "murmur2"
hash = "3722527620"

[update]
[update.curseforge]
file-id = 3398487
project-id = 317514
release-channel = "beta"
