name = "Patchouli (Fabric)"
filename = "Patchouli-1.16.4-53-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3362/798/Patchouli-1.16.4-53-FABRIC.jar"
hash-format = "murmur2"
hash = "265497884"

[update]
[update.curseforge]
file-id = 3362798
project-id = 393236
release-channel = "beta"
