name = "Sit (Fabric)"
filename = "sit-1.16.5-11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3303/128/sit-1.16.5-11.jar"
hash-format = "murmur2"
hash = "232239178"

[update]
[update.curseforge]
file-id = 3303128
project-id = 328163
release-channel = "beta"
