name = "Spellbound Enchantments"
filename = "spellbound-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3337/221/spellbound-1.3.0.jar"
hash-format = "murmur2"
hash = "944130542"

[update]
[update.curseforge]
file-id = 3337221
project-id = 434965
release-channel = "beta"
