name = "StackablePotions"
filename = "Stackable Potions-FABRIC-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3008/809/Stackable Potions-FABRIC-1.0.0.jar"
hash-format = "murmur2"
hash = "4084126843"

[update]
[update.curseforge]
file-id = 3008809
project-id = 396596
release-channel = "beta"
